services:
  stella-vslam-pc:
    build:
        context: ..
        dockerfile: docker/Dockerfile.pc
    image: stella-vslam-pc
    container_name: stella-vslam-pc
    privileged: true
    network_mode: host
    ipc: host
    init: true
    gpus: all
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: ${DISPLAY}
      ROS_DOMAIN_ID: 0
      RMW_IMPLEMENTATION: rmw_fastrtps_cpp
      FASTDDS_BUILTIN_TRANSPORTS: UDPv4
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /tmp/.X11-unix/:/tmp/.X11-unix/
      - ../../recordings:/ros2_ws/recordings
    entrypoint: /ros_entrypoint.sh
    command: ros2 launch stella_vslam_ros offline_slam.launch.py
